Repository semicolondsm/Unknown-Backend, pull requests merged in 2021-11, with the labels that each got.

#1 [#1] 🔀 :: 프로젝트 세팅
  README.md
  build.gradle
  src/main/java/com/example/unknown/entity/jwt/RefreshTokenEntity.java
  src/main/java/com/example/unknown/entity/repository/jwt/RefreshTokenRepository.java
  src/main/java/com/example/unknown/entity/repository/user/UserRepository.java
  src/main/java/com/example/unknown/entity/user/Role.java
  src/main/java/com/example/unknown/entity/user/User.java
  src/main/resources/application.yml
Labels: 프로젝트 설정, 기능 추가

#11 [#2] 🔀 :: 브런치 병합
  README.md
  build.gradle
  src/main/java/com/example/unknown/entity/jwt/RefreshTokenEntity.java
  src/main/java/com/example/unknown/entity/repository/jwt/RefreshTokenRepository.java
  src/main/java/com/example/unknown/entity/repository/user/UserRepository.java
  src/main/java/com/example/unknown/entity/user/Role.java
  src/main/java/com/example/unknown/entity/user/User.java
  src/main/resources/application.yml
Labels: 프로젝트 설정

#12 [#4] 🔀 :: 피처 브런치 에서 커밋 확인
  README.md
  build.gradle
  src/main/java/com/example/unknown/entity/jwt/RefreshTokenEntity.java
  src/main/java/com/example/unknown/entity/repository/jwt/RefreshTokenRepository.java
  src/main/java/com/example/unknown/entity/repository/user/UserRepository.java
  src/main/java/com/example/unknown/entity/user/Role.java
  src/main/java/com/example/unknown/entity/user/User.java
  src/main/resources/application.yml
Labels: 프로젝트 설정

#14 [#5] 🔀 :: 커밋 꼬임
  README.md
  build.gradle
Labels: 프로젝트 설정, 기능 추가

#15 [#6] 🔀 :: JWT 필터, config 기능 구현
  build.gradle
  src/main/java/com/example/unknown/config/FilterConfig.java
  src/main/java/com/example/unknown/entity/repository/user/UserRepository.java
  src/main/java/com/example/unknown/exception/CustomException.java
  src/main/java/com/example/unknown/exception/InvalidTokenException.java
  src/main/java/com/example/unknown/security/jwt/Auth/AuthUserDetailsService.java
  src/main/java/com/example/unknown/security/jwt/Auth/TokenFilter.java
  src/main/java/com/example/unknown/security/jwt/JwtProvider.java
  src/main/java/com/example/unknown/util/HttpStatusResponseEntity.java
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: 테스트 추가, 리팩토링, 프로젝트 설정, 기능 추가

#16 [#7] 🔀 :: jwt CONFIG 생성
  src/main/java/com/example/unknown/config/SecurityConfig.java
Labels: 기능 추가

#23 🔀 :: Exception 처리 수정
  src/main/java/com/example/unknown/exception/CustomException.java
  src/main/java/com/example/unknown/exception/InvalidTokenException.java
  src/main/java/com/example/unknown/global/config/FilterConfig.java
  src/main/java/com/example/unknown/global/error/ErrorCode.java
  src/main/java/com/example/unknown/global/error/ErrorResponse.java
  src/main/java/com/example/unknown/global/error/GlobalExceptionHandler.java
  src/main/java/com/example/unknown/global/error/UnknownException.java
  src/main/java/com/example/unknown/global/security/Auth/AuthUserDetailsService.java
  src/main/java/com/example/unknown/global/security/Auth/TokenFilter.java
  src/main/java/com/example/unknown/global/security/jwt/JwtProvider.java
  src/main/java/com/example/unknown/service/UserServiceImpl.java
Labels: 프로젝트 설정

#27 🔀 :: (#13) 프로젝트 package 다시 설정
  build.gradle
  src/main/java/com/example/unknown/config/FilterConfig.java
  src/main/java/com/example/unknown/controller/UserController.java
  src/main/java/com/example/unknown/dto/request/UserRequest.java
  src/main/java/com/example/unknown/dto/response/TokenResponse.java
  src/main/java/com/example/unknown/entity/auth/Role.java
  src/main/java/com/example/unknown/entity/auth/User.java
  src/main/java/com/example/unknown/entity/repository/auth/UserRepository.java
  src/main/java/com/example/unknown/entity/repository/user/UserRepository.java
  src/main/java/com/example/unknown/exception/CustomException.java
  src/main/java/com/example/unknown/exception/InvalidPasswordException.java
  src/main/java/com/example/unknown/exception/InvalidRoleException.java
  src/main/java/com/example/unknown/exception/InvalidTokenException.java
  src/main/java/com/example/unknown/exception/UserExistsException.java
  src/main/java/com/example/unknown/exception/UserNotExistsException.java
  src/main/java/com/example/unknown/global/error/ErrorCode.java
  src/main/java/com/example/unknown/security/jwt/Auth/AuthUserDetailsService.java
  src/main/java/com/example/unknown/security/jwt/Auth/TokenFilter.java
  src/main/java/com/example/unknown/security/jwt/JwtProvider.java
  src/main/java/com/example/unknown/service/UserService.java
  src/main/java/com/example/unknown/service/UserServiceImpl.java
  src/main/java/com/example/unknown/util/HttpStatusResponseEntity.java
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: 프로젝트 설정

#28 🔀 :: (#1) fix User Login logic
  src/main/java/com/example/unknown/dto/request/UserRequest.java
  src/main/java/com/example/unknown/dto/response/TokenResponse.java
  src/main/java/com/example/unknown/service/UserServiceImpl.java
Labels: 리팩토링

#35 🔀 :: (#7) Verify Code
  src/main/java/com/example/unknown/dto/request/VerifyCodeRequest.java
  src/main/java/com/example/unknown/exception/InvalidCodeException.java
  src/main/java/com/example/unknown/global/error/ErrorCode.java
  src/main/java/com/example/unknown/service/MailService.java
  src/main/java/com/example/unknown/service/MailServiceImpl.java
Labels: 기능 추가

#30 🔀 :: (#3) id를 email수정
  src/main/java/com/example/unknown/service/UserServiceImpl.java
Labels: 리팩토링, 프로젝트 설정

#42 🔀 :: (#11) UserController 수정
  src/main/java/com/example/unknown/controller/UserController.java
Labels: chore

#41 🔀 :: (#10) Mail Yml 설정
  src/main/resources/application.yml
Labels: 프로젝트 설정

#37 🔀 :: (#8) Change Password Logic
  src/main/java/com/example/unknown/dto/request/ChangePasswordRequest.java
  src/main/java/com/example/unknown/service/UserServiceImpl.java
Labels: 기능 추가

#43 🔀 :: (#12) Mail Controller 분리
  src/main/java/com/example/unknown/controller/MailController.java
  src/main/java/com/example/unknown/controller/UserController.java
Labels: 리팩토링

#33 🔀 :: (#6) docker 설정
  Docker-compose.yml
  build.gradle
  src/main/java/com/example/unknown/config/RedisConfig.java
  src/main/java/com/example/unknown/entity/BaseTimeEntity.java
  src/main/java/com/example/unknown/entity/post/Post.java
  src/main/resources/application.yml
Labels: 프로젝트 설정

#40 🔀 :: (#9) Logging 설정
  src/main/java/com/example/unknown/security/FilterConfig.java
  src/main/java/com/example/unknown/security/SecurityConfig.java
  src/main/java/com/example/unknown/security/logging/LogWriter.java
  src/main/java/com/example/unknown/security/logging/RequestLogger.java
  src/main/java/com/example/unknown/security/logging/RequestWrapper.java
  src/main/resources/application.yml
Labels: 리팩토링, 프로젝트 설정, 기능 추가

#44 🔀 :: (#10) apache poi 의존성 추가
  build.gradle
Labels: 프로젝트 설정

#46 🔀 :: (#13) 게시물 추가 api
  src/main/java/com/example/unknown/controller/PostController.java
  src/main/java/com/example/unknown/dto/request/PostRequest.java
  src/main/java/com/example/unknown/service/PostService.java
Labels: 기능 추가

#48 🔀 :: (#15) 모든 오류 수정
  build.gradle
  src/main/java/com/example/unknown/config/RedisConfig.java
  src/main/java/com/example/unknown/controller/PostController.java
  src/main/java/com/example/unknown/entity/auth/Admin.java
  src/main/java/com/example/unknown/entity/auth/User.java
  src/main/java/com/example/unknown/entity/post/Post.java
  src/main/java/com/example/unknown/entity/repository/auth/UserRepository.java
  src/main/java/com/example/unknown/security/SecurityConfig.java
  src/main/java/com/example/unknown/security/jwt/Auth/AuthUserDetailsService.java
  src/main/java/com/example/unknown/security/jwt/Auth/TokenFilter.java
  src/main/java/com/example/unknown/security/jwt/JwtProvider.java
  src/main/java/com/example/unknown/security/logging/LogWriter.java
  src/main/java/com/example/unknown/security/logging/RequestLogger.java
  src/main/java/com/example/unknown/security/logging/RequestWrapper.java
  src/main/java/com/example/unknown/service/PostService.java
  src/main/resources/application.yml
Labels: 리팩토링, 프로젝트 설정, chore

#51 🔀 :: (#21) 리펙토링
  src/main/java/com/example/unknown/domain/User/domain/repository/UserRepository.java
  src/main/java/com/example/unknown/domain/User/service/UserServiceImpl.java
Labels: 리팩토링

#52 🔀 :: (#21) user password fix
  src/main/java/com/example/unknown/domain/User/presentation/dto/request/UserRequest.java
  src/main/java/com/example/unknown/domain/User/service/UserServiceImpl.java
Labels: 리팩토링, chore

#53 🔀 :: (#22) Mail Verify fix
  src/main/java/com/example/unknown/domain/Mail/service/MailServiceImpl.java
  src/main/java/com/example/unknown/domain/User/domain/AuthCode.java
Labels: 리팩토링, chore

#55 🔀 :: (#24) Admin Facade
  src/main/java/com/example/unknown/domain/Admin/exception/AdminExistsException.java
  src/main/java/com/example/unknown/domain/Admin/facade/AdminFacade.java
  src/main/java/com/example/unknown/domain/Admin/service/AdminServiceImpl.java
  src/main/java/com/example/unknown/global/error/exception/ErrorCode.java
Labels: 기능 추가

#54 🔀 :: (#23) UserFacade & AuthCodeFacade
  src/main/java/com/example/unknown/domain/User/facade/UserAuthCodeFacade.java
  src/main/java/com/example/unknown/domain/User/facade/UserFacade.java
  src/main/java/com/example/unknown/domain/User/service/UserServiceImpl.java
Labels: 기능 추가

#56 🔀 :: (#25) 피드 @LOB 어노테이션 변경
  src/main/java/com/example/unknown/domain/Feed/domain/Feed.java
  src/main/java/com/example/unknown/domain/comment/domain/Comment.java
Labels: 리팩토링

#57 🔀 :: (#26) Feed, User Join 삭제
  src/main/java/com/example/unknown/domain/Feed/domain/Feed.java
  src/main/java/com/example/unknown/domain/User/domain/User.java
Labels: 리팩토링, chore

#58 🔀 :: (#27) 이서준선배님의 조언
  src/main/java/com/example/unknown/domain/Admin/domain/Admin.java
  src/main/java/com/example/unknown/domain/User/domain/User.java
  src/main/java/com/example/unknown/domain/comment/domain/Comment.java
  src/main/java/com/example/unknown/global/security/SecurityConfig.java
Labels: 리팩토링

#59 🔀 :: (#28) Feed 기본 구조 생성
  src/main/java/com/example/unknown/domain/Feed/domain/Feed.java
  src/main/java/com/example/unknown/domain/Feed/domain/repository/FeedRepository.java
  src/main/java/com/example/unknown/domain/Feed/presentation/FeedController.java
  src/main/java/com/example/unknown/domain/Feed/service/.gitkeep
  src/main/java/com/example/unknown/domain/Feed/service/FeedService.java
  src/main/java/com/example/unknown/domain/Feed/service/FeedServiceImpl.java
Labels: 기능 추가

#60 🔀 :: (#26) 수정한 코드 26번 브런치로 머지
  src/main/java/com/example/unknown/domain/Admin/domain/Admin.java
  src/main/java/com/example/unknown/domain/Admin/domain/repository/AdminRepository.java
  src/main/java/com/example/unknown/domain/Admin/facade/AdminFacade.java
  src/main/java/com/example/unknown/domain/Admin/service/AdminServiceImpl.java
  src/main/java/com/example/unknown/domain/Feed/domain/Feed.java
  src/main/java/com/example/unknown/domain/Feed/domain/repository/.gitkeep
  src/main/java/com/example/unknown/domain/Feed/domain/repository/FeedRepository.java
  src/main/java/com/example/unknown/domain/Feed/domain/types/.gitkeep
  src/main/java/com/example/unknown/domain/Feed/exception/.gitkeep
  src/main/java/com/example/unknown/domain/Feed/facade/.gitkeep
  src/main/java/com/example/unknown/domain/Feed/presentation/FeedController.java
  src/main/java/com/example/unknown/domain/Feed/presentation/dto/request/.gitkeep
  src/main/java/com/example/unknown/domain/Feed/presentation/dto/request/PostRequest.java
  src/main/java/com/example/unknown/domain/Feed/presentation/dto/response/.gitkeep
  src/main/java/com/example/unknown/domain/Feed/service/FeedService.java
  src/main/java/com/example/unknown/domain/Feed/service/FeedServiceImpl.java
  src/main/java/com/example/unknown/domain/Mail/facade/.gitkeep
  src/main/java/com/example/unknown/domain/User/domain/User.java
  src/main/java/com/example/unknown/domain/comment/domain/Comment.java
  src/main/java/com/example/unknown/global/security/SecurityConfig.java
Labels: 리팩토링

#63 🔀 :: (#30) UserFacade & UserService
  src/main/java/com/example/unknown/domain/User/facade/UserFacade.java
  src/main/java/com/example/unknown/domain/User/service/UserServiceImpl.java
Labels: 리팩토링, chore

#62 🔀 :: (#29) User Password로직 수정
  src/main/java/com/example/unknown/domain/Mail/domain/AuthCode.java
  src/main/java/com/example/unknown/domain/Mail/domain/repository/AuthCodeRepository.java
  src/main/java/com/example/unknown/domain/Mail/presentation/MailController.java
  src/main/java/com/example/unknown/domain/Mail/presentation/dto/request/SendEmailRequest.java
  src/main/java/com/example/unknown/domain/Mail/service/MailServiceImpl.java
  src/main/java/com/example/unknown/domain/User/facade/UserAuthCodeFacade.java
  src/main/java/com/example/unknown/domain/User/presentation/dto/request/ChangePasswordRequest.java
Labels: 리팩토링, chore

#61 🔀 :: (#29) 댓글 추가 api
  src/main/java/com/example/unknown/domain/comment/domain/Comment.java
  src/main/java/com/example/unknown/domain/comment/domain/repository/CommentRepository.java
  src/main/java/com/example/unknown/domain/comment/presentation/CommentController.java
  src/main/java/com/example/unknown/domain/comment/presentation/dto/CommentRequest.java
  src/main/java/com/example/unknown/domain/comment/presentation/dto/request/CommentRequest.java
  src/main/java/com/example/unknown/domain/comment/presentation/dto/request/EditCommentRequest.java
  src/main/java/com/example/unknown/domain/comment/presentation/dto/response/CommentResponse.java
  src/main/java/com/example/unknown/domain/comment/service/CommentService.java
  src/main/java/com/example/unknown/domain/comment/service/CommentServiceImpl.java
  src/main/java/com/example/unknown/global/error/exception/ErrorCode.java
  src/main/java/com/example/unknown/global/exception/CommentNotFoundException.java
Labels: 리팩토링, 기능 추가

#67 🔀 :: (#33) 댓글 수정 api
  src/main/java/com/example/unknown/domain/comment/exception/CommentNotFoundException.java
  src/main/java/com/example/unknown/domain/comment/presentation/CommentController.java
  src/main/java/com/example/unknown/domain/comment/presentation/dto/request/EditCommentRequest.java
  src/main/java/com/example/unknown/domain/comment/presentation/dto/request/RemoveCommentRequest.java
  src/main/java/com/example/unknown/domain/comment/service/CommentService.java
  src/main/java/com/example/unknown/global/exception/CommentNotFoundException.java
Labels: 기능 추가
