Repository semicolondsm/Unknown-Backend, pull requests merged in 2021-12, with the labels that each got.

#65 🔀 :: (#32) Admin 회원가입 삭제 & Admin Facade수정
  src/main/java/com/example/unknown/domain/Admin/facade/AdminFacade.java
  src/main/java/com/example/unknown/domain/Admin/service/AdminService.java
  src/main/java/com/example/unknown/domain/Admin/service/AdminServiceImpl.java
Labels: 리팩토링, chore

#66 🔀 :: (#31) User Facade 수정
  src/main/java/com/example/unknown/domain/User/facade/UserFacade.java
  src/main/java/com/example/unknown/domain/User/service/UserServiceImpl.java
Labels: 리팩토링, chore

#64 🔀 :: (#31) Feed
  src/main/java/com/example/unknown/domain/Feed/domain/Category.java
  src/main/java/com/example/unknown/domain/Feed/domain/repository/.gitkeep
  src/main/java/com/example/unknown/domain/Feed/domain/repository/FeedRepository.java
  src/main/java/com/example/unknown/domain/Feed/domain/types/.gitkeep
  src/main/java/com/example/unknown/domain/Feed/domain/types/LanguageRole.java
  src/main/java/com/example/unknown/domain/Feed/domain/types/SubjectRole.java
  src/main/java/com/example/unknown/domain/Feed/exception/.gitkeep
  src/main/java/com/example/unknown/domain/Feed/facade/.gitkeep
  src/main/java/com/example/unknown/domain/Feed/presentation/FeedController.java
  src/main/java/com/example/unknown/domain/Feed/presentation/dto/request/.gitkeep
  src/main/java/com/example/unknown/domain/Feed/presentation/dto/request/CreateFeedRequest.java
  src/main/java/com/example/unknown/domain/Feed/presentation/dto/request/DeleteFeedRequest.java
  src/main/java/com/example/unknown/domain/Feed/presentation/dto/request/UpdateDescriptionRequest.java
  src/main/java/com/example/unknown/domain/Feed/presentation/dto/request/UpdateTitleRequest.java
  src/main/java/com/example/unknown/domain/Feed/presentation/dto/response/.gitkeep
  src/main/java/com/example/unknown/domain/Feed/service/FeedService.java
  src/main/java/com/example/unknown/domain/Feed/service/FeedServiceImpl.java
Labels: 기능 추가

#70 🔀 :: (#34) admin password 로직 변경
  src/main/java/com/example/unknown/domain/Admin/service/AdminServiceImpl.java
Labels: 리팩토링, chore

#71 🔀 :: (#35) Feed Exception 처리
  src/main/java/com/example/unknown/domain/Feed/exception/FeedNotExistsException.java
  src/main/java/com/example/unknown/domain/Feed/facade/FeedFacade.java
  src/main/java/com/example/unknown/domain/Feed/service/FeedServiceImpl.java
  src/main/java/com/example/unknown/global/error/exception/ErrorCode.java
Labels: 리팩토링

#68 🔀 :: (#33) 댓글 삭제 api
  src/main/java/com/example/unknown/domain/comment/presentation/CommentController.java
  src/main/java/com/example/unknown/domain/comment/presentation/dto/request/RemoveCommentRequest.java
  src/main/java/com/example/unknown/domain/comment/service/CommentServiceImpl.java
Labels: 기능 추가

#72 🔀 :: (#34) FeedService 유저 상속 삭제
  src/main/java/com/example/unknown/domain/comment/presentation/dto/request/RemoveCommentRequest.java
  src/main/java/com/example/unknown/domain/comment/service/CommentServiceImpl.java
Labels: 기능 추가

#74 🔀 :: (#38) Category
  src/main/java/com/example/unknown/domain/Feed/domain/Category.java
  src/main/java/com/example/unknown/domain/Feed/domain/repository/CategoryRepository.java
  src/main/java/com/example/unknown/domain/Feed/domain/repository/FeedRepository.java
  src/main/java/com/example/unknown/domain/Feed/domain/types/SubjectRole.java
  src/main/java/com/example/unknown/domain/Feed/exception/FeedNotExistsException.java
  src/main/java/com/example/unknown/domain/Feed/presentation/CategoryController.java
  src/main/java/com/example/unknown/domain/Feed/presentation/dto/response/.gitkeep
  src/main/java/com/example/unknown/domain/Feed/service/CategoryService.java
  src/main/java/com/example/unknown/domain/Feed/service/CategoryServiceImpl.java
  src/main/java/com/example/unknown/domain/User/presentation/dto/request/UserRequest.java
Labels: 기능 추가

#73 🔀 :: (#37) Comment Facade사용
  src/main/java/com/example/unknown/domain/comment/facade/CommentFacade.java
  src/main/java/com/example/unknown/domain/comment/service/CommentServiceImpl.java
Labels: 리팩토링, chore

#75 🔀 :: (#38) email verify Code 형식 수정
  build.gradle
  src/main/java/com/example/unknown/domain/Mail/service/MailServiceImpl.java
Labels: 리팩토링, chore

#76 🔀 :: (#39) 안쓰는 코드 정리
  src/main/java/com/example/unknown/domain/Mail/service/MailServiceImpl.java
  src/main/java/com/example/unknown/domain/User/presentation/UserController.java
  src/main/java/com/example/unknown/domain/User/presentation/dto/request/UserRequest.java
Labels: chore

#78 🔀 :: (#41) getCommentById -> isAlreadyExists
  src/main/java/com/example/unknown/domain/comment/service/CommentServiceImpl.java
Labels: chore

#79 🔀 :: (#42) SignUp, ChangePassword 후 AuthCode 삭제
  src/main/java/com/example/unknown/domain/User/facade/UserAuthCodeFacade.java
  src/main/java/com/example/unknown/domain/User/service/UserServiceImpl.java
Labels: 리팩토링, chore

#81 🔀 :: (#44) Verify Message 구조 변경
  src/main/java/com/example/unknown/domain/User/service/UserServiceImpl.java
  src/main/java/com/example/unknown/global/error/exception/ErrorCode.java
  src/main/java/com/example/unknown/global/exception/InvalidMessageException.java
Labels: chore

#80 🔀 :: (#43) Mail Send "" -> null
  src/main/java/com/example/unknown/domain/Mail/service/MailServiceImpl.java
Labels: chore

#82 🔀 :: (#45) User와 Feed 관계 설정
  src/main/java/com/example/unknown/domain/Feed/domain/Feed.java
  src/main/java/com/example/unknown/domain/User/domain/User.java
Labels: 기능 추가, chore

#83 🔀 :: Feed Api 변경 및 리팩토링
  src/main/java/com/example/unknown/domain/Feed/domain/Category.java
  src/main/java/com/example/unknown/domain/Feed/domain/Feed.java
  src/main/java/com/example/unknown/domain/Feed/domain/repository/CategoryRepository.java
  src/main/java/com/example/unknown/domain/Feed/domain/repository/FeedRepository.java
  src/main/java/com/example/unknown/domain/Feed/domain/types/LanguageRole.java
  src/main/java/com/example/unknown/domain/Feed/exception/CategoryNotFoundException.java
  src/main/java/com/example/unknown/domain/Feed/facade/FeedFacade.java
  src/main/java/com/example/unknown/domain/Feed/presentation/CategoryController.java
  src/main/java/com/example/unknown/domain/Feed/presentation/FeedController.java
  src/main/java/com/example/unknown/domain/Feed/presentation/dto/request/CreateFeedRequest.java
  src/main/java/com/example/unknown/domain/Feed/presentation/dto/request/DeleteFeedRequest.java
  src/main/java/com/example/unknown/domain/Feed/presentation/dto/request/ModifyFeedRequest.java
  src/main/java/com/example/unknown/domain/Feed/presentation/dto/request/PostFeedRequest.java
  src/main/java/com/example/unknown/domain/Feed/presentation/dto/request/UpdateDescriptionRequest.java
  src/main/java/com/example/unknown/domain/Feed/presentation/dto/request/UpdateTitleRequest.java
  src/main/java/com/example/unknown/domain/Feed/presentation/dto/response/FeedResponse.java
  src/main/java/com/example/unknown/domain/Feed/service/CategoryService.java
  src/main/java/com/example/unknown/domain/Feed/service/CategoryServiceImpl.java
  src/main/java/com/example/unknown/domain/Feed/service/FeedService.java
  src/main/java/com/example/unknown/domain/Feed/service/FeedServiceImpl.java
  src/main/java/com/example/unknown/domain/User/exception/CertificateNotFoundException.java
  src/main/java/com/example/unknown/domain/User/exception/UserNotFoundException.java
  src/main/java/com/example/unknown/domain/User/facade/UserFacade.java
  src/main/java/com/example/unknown/domain/User/service/UserServiceImpl.java
  src/main/java/com/example/unknown/domain/comment/service/CommentServiceImpl.java
  src/main/java/com/example/unknown/global/error/exception/ErrorCode.java
Labels: 리팩토링

#87 🔀 :: (#47) User gitHubId 추가
  src/main/java/com/example/unknown/domain/User/domain/User.java
  src/main/java/com/example/unknown/domain/User/presentation/dto/request/UserRequest.java
  src/main/java/com/example/unknown/domain/User/service/UserServiceImpl.java
Labels: 기능 추가, chore

#85 🔀 :: Comment 리팩토링
  src/main/java/com/example/unknown/domain/Feed/presentation/dto/request/ModifyFeedRequest.java
  src/main/java/com/example/unknown/domain/Feed/presentation/dto/request/PostFeedRequest.java
  src/main/java/com/example/unknown/domain/Feed/service/FeedService.java
  src/main/java/com/example/unknown/domain/Feed/service/FeedServiceImpl.java
  src/main/java/com/example/unknown/domain/comment/domain/Comment.java
  src/main/java/com/example/unknown/domain/comment/facade/CommentFacade.java
  src/main/java/com/example/unknown/domain/comment/presentation/CommentController.java
  src/main/java/com/example/unknown/domain/comment/presentation/dto/request/EditCommentRequest.java
  src/main/java/com/example/unknown/domain/comment/presentation/dto/request/PostCommentRequest.java
  src/main/java/com/example/unknown/domain/comment/service/CommentService.java
  src/main/java/com/example/unknown/domain/comment/service/CommentServiceImpl.java
Labels: 리팩토링

#88 🔀 :: (#49) Feed Facade & ServiceImpl 수정
  src/main/java/com/example/unknown/domain/Feed/domain/repository/FeedRepository.java
  src/main/java/com/example/unknown/domain/Feed/facade/FeedFacade.java
  src/main/java/com/example/unknown/domain/Feed/service/FeedServiceImpl.java
Labels: chore

#90 🔀 :: (#50) FeedServiceImpl modify
  src/main/java/com/example/unknown/domain/Feed/service/FeedServiceImpl.java
Labels: chore

#91 🔀 :: (#51) FeedServiceImpl getFeed refactoring
  src/main/java/com/example/unknown/domain/Feed/service/FeedServiceImpl.java
Labels: 리팩토링

#92 🔀 :: (#52) User Refresh_Token 재발급 로직 추가
  src/main/java/com/example/unknown/domain/Refresh_token/domain/RefreshToken.java
  src/main/java/com/example/unknown/domain/Refresh_token/domain/repository/RefreshTokenRepository.java
  src/main/java/com/example/unknown/domain/User/presentation/UserController.java
  src/main/java/com/example/unknown/domain/User/presentation/dto/request/RefreshTokenRequest.java
  src/main/java/com/example/unknown/domain/User/service/UserService.java
  src/main/java/com/example/unknown/domain/User/service/UserServiceImpl.java
  src/main/java/com/example/unknown/global/security/jwt/JwtTokenProvider.java
Labels: 기능 추가

#93 🔀 :: (#53) ErrorCode & yml 수정
  src/main/java/com/example/unknown/global/error/exception/ErrorCode.java
  src/main/resources/application.yml
Labels: chore

#94 🔀 :: (#54) User 리프레쉬 토근 재발급
  src/main/java/com/example/unknown/domain/Refresh_token/domain/RefreshToken.java
  src/main/java/com/example/unknown/domain/Refresh_token/domain/repository/RefreshTokenRepository.java
  src/main/java/com/example/unknown/domain/User/facade/UserFacade.java
  src/main/java/com/example/unknown/domain/User/presentation/dto/request/RefreshTokenRequest.java
  src/main/java/com/example/unknown/global/error/exception/ErrorCode.java
  src/main/java/com/example/unknown/global/security/jwt/JwtProperties.java
  src/main/java/com/example/unknown/global/security/jwt/JwtTokenProvider.java
Labels: 기능 추가, chore

#95 🔀 :: (#55) 유저 회원가입 & 로그인 DTO 수정
  src/main/java/com/example/unknown/domain/User/presentation/UserController.java
  src/main/java/com/example/unknown/domain/User/presentation/dto/request/UserLoginRequest.java
  src/main/java/com/example/unknown/domain/User/presentation/dto/request/UserSignUpRequest.java
  src/main/java/com/example/unknown/domain/User/service/UserService.java
  src/main/java/com/example/unknown/domain/User/service/UserServiceImpl.java
Labels: 리팩토링, chore
